# Generated by Django 4.1.7 on 2023-02-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
