# Generated by Django 4.1.6 on 2023-02-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("News", "0002_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
