# Generated by Django 4.1.6 on 2023-02-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("News", "0004_alter_news_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="link",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
