# Generated by Django 4.1.6 on 2023-02-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("News", "0005_news_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
