# Generated by Django 4.1.7 on 2023-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0007_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
