# Generated by Django 4.1.7 on 2023-02-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0009_alter_post_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
