# Generated by Django 4.1.7 on 2023-02-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0010_remove_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
