# Generated by Django 4.1.7 on 2023-02-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0011_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="News.category"
            ),
        ),
    ]
